### ISSUE TITLE
Enhancement:

### ISSUE THREAD

**Issue by timothyslau** [stanford-futuredata/Willump#7]
Would you mind adding a simple example of it being used to the `readme` file?
Or a link to a notebook?

**Comment by kraftp** [comment]
Sorry about being late to respond here!  I've actually been working on a new, simpler version of the project now released here:  https://github.com/stanford-futuredata/Willump-Simple.  The new version has a [tutorial](https://github.com/stanford-futuredata/Willump-Simple/blob/master/notebooks/tutorial-notebook.ipynb) and [demo](https://github.com/stanford-futuredata/Willump-Simple/blob/master/notebooks/explanation-notebook.ipynb) notebook that you might be interested in.
